### ISSUE TITLE
We don't get is_subscribed, is_recommended, is_bookmarked

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#105]
Series returned in the FetchSubscriptions endpoint don't have is_subscribed field

**Comment by natashaarmbrust** [comment]
I know we know they are subscribed but for consistency can you add this field in

**Comment by Jma353** [comment]
Adding this field unnecessarily doesn't really make sense - we should be able to handle a lack of this field on client.

**Comment by natashaarmbrust** [comment]
yea you are so right, fixed it just now.
