### ISSUE TITLE
 genre searching

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#109]

**Comment by Jma353** [comment]
Do we still need this?

**Comment by natashaarmbrust** [comment]
Nope! We will now have listing all / top episodes and series by genre

**Comment by natashaarmbrust** [comment]
<img width="284" alt="screen shot 2017-11-15 at 4 34 42 pm" src="https://user-images.githubusercontent.com/14966713/32861539-010e93b8-ca23-11e7-933e-569a6308ad9c.png">
<img width="272" alt="screen shot 2017-11-15 at 4 35 05 pm" src="https://user-images.githubusercontent.com/14966713/32861543-0230dbc0-ca23-11e7-89d6-e2bd65a501c6.png">

**Comment by DanielNosrati** [comment]
#188
