### ISSUE TITLE
DB transaction failure when trying to subscribe to series

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#114]
<img width="257" alt="screen shot 2017-10-06 at 2 03 05 am" src="https://user-images.githubusercontent.com/14966713/31265063-d8b4fa72-aa3a-11e7-9733-f31542fc77d9.png">
<img width="369" alt="screen shot 2017-10-06 at 2 03 10 am" src="https://user-images.githubusercontent.com/14966713/31265065-da0931a4-aa3a-11e7-8888-96d01f867548.png">

**Comment by natashaarmbrust** [comment]
This only has happened for me for this series

**Comment by Jma353** [comment]
Does it repeatedly happen?

**Comment by Jma353** [comment]
@natashaarmbrust it looks like you are already subscribed to this - if you try subscribing again, this error is expected as that subscription already exists.

**Comment by natashaarmbrust** [comment]
This was my first time subscribing

**Comment by natashaarmbrust** [comment]
I can't reproduce the error so let's close this for now, but just something to be aware of
