### ISSUE TITLE
Episode date labels are very inconsistent ... anyway we can standardize?

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#117]
<img width="252" alt="screen shot 2017-10-06 at 8 53 03 pm" src="https://user-images.githubusercontent.com/14966713/31303673-a29375ae-aadf-11e7-9294-64a35ebd8b5e.png">

**Comment by Jma353** [comment]
This would involve standardizing for every episode on iTunes.... something that's not super feasible as we get this info from a phenomenally varied set of sources.  Also by date label, do you mean the actual date format??  I don't see the discrepancy between the two cells.

**Comment by natashaarmbrust** [comment]
fixed with listening history feature
