### ISSUE TITLE
DB transaction failure b/c inconsistent state 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#118]
With this episode (and a couple others), I am having the issue that the request returns "isBookmarked" to be false but it is actually bookmarked (see the second screen below from the Bookmark Tab). So when I try to bookmark it on the feed it gives me an error because obviously, I am trying to bookmark something that is already bookmarked 

<img width="475" alt="screen shot 2017-10-08 at 8 48 56 pm" src="https://user-images.githubusercontent.com/14966713/31322729-591226fe-ac6b-11e7-9d1e-e975d6b939bc.png">

<img width="296" alt="screen shot 2017-10-08 at 8 49 30 pm" src="https://user-images.githubusercontent.com/14966713/31322730-5aeacc74-ac6b-11e7-86b9-b0a378497dec.png">

Screens above should have all info about the episode that was causing this issue. It would also be nice to have distinct error messages for cases like these.. such as "DB transaction failure: trying to bookmark already bookmarked episode {id}"

**Comment by ChenJesse** [comment]
https://github.com/cuappdev/podcast-backend/pull/121 addresses the core issue

I looked into creating better error messages but its more complicated than I thought (b/c of SQLAlchemy abstractions), we can revisit it later if needed
