### ISSUE TITLE
Series / Episodes by Topic / Subtopic ordered by Newly Released / Popular

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#120]
<img width="247" alt="screen shot 2017-10-11 at 6 16 05 pm" src="https://user-images.githubusercontent.com/14966713/31469609-4616e034-aeb0-11e7-9448-a4cc7e04ac86.png">

**Comment by DanielNosrati** [comment]
This is the discover feature that was implemented in the PR #188 . Closing it.
