### ISSUE TITLE
Include series title in episode data

### ISSUE THREAD

**Issue by mindylou** [cuappdev/podcast-backend#125]
![image](https://user-images.githubusercontent.com/20246620/31857903-f72b9c16-b6b7-11e7-982d-03cd33b1f12b.png)
![image](https://user-images.githubusercontent.com/20246620/31857904-fbcd9a44-b6b7-11e7-92c4-76bd82657567.png)

- currently not displaying the series title (eg. "Planet Money" or "Design Details")

**Comment by Jma353** [comment]
When one requests an episode, we always return the entire series along with it unless otherwise requested.  What endpoint is hit to populate the content of that view?

**Comment by ChenJesse** [comment]
Hmm I don't think the the entire series schema was ever nested in the episode schema (maybe we felt it was too redundant), I made a PR a few weeks ago to embed the image url with a select few fields, we can just add title to it

PR mentioned: https://github.com/cuappdev/podcast-backend/pull/104/files

**Comment by Jma353** [comment]
Oh sorry looked at that quickly - we should add title then.

**Comment by Jma353** [comment]
This change is now live
