### ISSUE TITLE
Discover endpoints 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#127]
We need endpoint to get top series on our app (number of subscribers is largest)
We need endpoint to get top episodes on our app (either recommended number or @kevingreer ML number to rank episodes)
<img width="337" alt="screen shot 2017-10-22 at 2 43 10 pm" src="https://user-images.githubusercontent.com/14966713/31865149-b73e5bc2-b737-11e7-9f76-12f4131e82a6.png">

**Comment by Jma353** [comment]
These are done + pushed
