### ISSUE TITLE
Topics 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#128]
We need an endpoint to get all topics (ex: Art, Entertainment, etc.) which are the big heading topics on iTunes search
We need an endpoint to get subtopics per topic (ex: Art -> Design, Visual Arts, etc.) and some notion of the parent topic because on iOS we will treat them all as the same but you guys need the difference between topic vs. subtopic 
<img width="354" alt="screen shot 2017-10-22 at 2 48 42 pm" src="https://user-images.githubusercontent.com/14966713/31865178-596becd4-b738-11e7-8ff2-1d01f3793495.png">
<img width="399" alt="screen shot 2017-10-22 at 2 48 37 pm" src="https://user-images.githubusercontent.com/14966713/31865180-5b15990e-b738-11e7-9f83-a4b602aa4b09.png">

**Comment by DanielNosrati** [comment]
#188
