### ISSUE TITLE
Episodes / Series by Topic 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#129]
We need endpoint for related topics to a topic (aka subtopics if topic is parent topic or other subtopics and parent topic if topic is subtopic)
We need endpoint for newly released episodes by topic
We need endpoint for series by topic (sorted by number of subscribers > # so we can do top series)

<img width="325" alt="screen shot 2017-10-22 at 3 08 01 pm" src="https://user-images.githubusercontent.com/14966713/31865296-d106390a-b73a-11e7-962c-810f6a6ca350.png">

**Comment by DanielNosrati** [comment]
#188
