### ISSUE TITLE
is_following in SearchPeople json result

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#131]
We should have a isFollowing field in this json .. this is the result when i try to search for a person
<img width="523" alt="screen shot 2017-10-23 at 1 13 22 am" src="https://user-images.githubusercontent.com/14966713/31873159-77c89522-b78f-11e7-90d8-e32271a8a06a.png">

**Comment by Jma353** [comment]
I can grab this quick task
