### ISSUE TITLE
followers endpoint -> need is_following 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#133]
We don't get is_following in the followers endpoint. I am following Drew but doesn't show up when I look at my followers. 
<img width="301" alt="screen shot 2017-10-26 at 2 00 43 pm" src="https://user-images.githubusercontent.com/14966713/32069148-4ac7cf06-ba56-11e7-8ae2-5eb1046a0090.png">
<img width="310" alt="screen shot 2017-10-26 at 2 00 48 pm" src="https://user-images.githubusercontent.com/14966713/32069150-4bda6548-ba56-11e7-82fe-5d19cf10bc50.png">
<img width="594" alt="screen shot 2017-10-26 at 2 01 05 pm" src="https://user-images.githubusercontent.com/14966713/32069151-4d1ac4c0-ba56-11e7-8d13-b5cec61ae8e0.png">

**Comment by natashaarmbrust** [comment]
same for Following!

**Comment by ChenJesse** [comment]
Addressed in https://github.com/cuappdev/podcast-backend/pull/136
