### ISSUE TITLE
Toggling series subscribe bug 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#137]
I subscribed to this series then tried to unsubscribe very shortly after and got this error
<img width="304" alt="screen shot 2017-10-28 at 12 23 30 am" src="https://user-images.githubusercontent.com/14966713/32131435-eb353886-bb7b-11e7-85f9-fa76a8e50389.png">
<img width="633" alt="screen shot 2017-10-28 at 12 23 16 am" src="https://user-images.githubusercontent.com/14966713/32131436-ec421898-bb7b-11e7-9bea-7789b53d742a.png">

**Comment by natashaarmbrust** [comment]
<img width="660" alt="screen shot 2017-11-02 at 1 32 07 am" src="https://user-images.githubusercontent.com/14966713/32311217-b611a8ec-bf6d-11e7-8ddf-5ed674be48ca.png">
Getting this again!! Please fixxxx

**Comment by DanielNosrati** [comment]
Most likely going to be a Joe fix, but if you can reproduce this and give us the requests you made then maybe Jesse or I can try to reproduce it on test and give it a look.

**Comment by Jma353** [comment]
I'll look into this - it's a transactional thing involving the ORM / DB.  I'm busy until mid-day tomorrow so won't be looking at it until then.

**Comment by DanielNosrati** [comment]
This has not appeared in a while. So I will consider this close until it reappears again.
@mindylou @jackthmp @drewsdunne let us see if this appears again
