### ISSUE TITLE
Search ITunes created_at bug

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#145]
Used Mindy's search ITunes branch to upload this podcast from ITunes. However, when I try to subscribe I get the error shown below
<img width="268" alt="screen shot 2017-11-01 at 11 57 25 am" src="https://user-images.githubusercontent.com/14966713/32283856-ed8ef9fe-befb-11e7-85e2-d203ea6a95a7.png">
<img width="504" alt="screen shot 2017-11-01 at 11 57 30 am" src="https://user-images.githubusercontent.com/14966713/32283858-ee8c3b5a-befb-11e7-8415-e09e0eab7d13.png">

**Comment by natashaarmbrust** [comment]
Also when I go to the series detail view I get empty episodes array (any chance we can fetch 
 episodes when we do the search iTunes)
<img width="255" alt="screen shot 2017-11-01 at 11 59 51 am" src="https://user-images.githubusercontent.com/14966713/32284032-5a15abf4-befc-11e7-800b-cfb9f9250b71.png">
<img width="432" alt="screen shot 2017-11-01 at 11 59 47 am" src="https://user-images.githubusercontent.com/14966713/32284038-5ca15198-befc-11e7-99b8-211e39359a42.png">

**Comment by Jma353** [comment]
Should be fixed with #146
