### ISSUE TITLE
Followers count

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#147]
<img width="616" alt="screen shot 2017-11-02 at 6 15 02 pm" src="https://user-images.githubusercontent.com/14966713/32352972-d35deaf0-bff9-11e7-9eff-f378e06f6524.png">
I am following mindy but her followers count is 0

**Comment by ChenJesse** [comment]
This is after we reset all the counts right?

And if so, I think some ppl had multiple accounts associated with their name, could you make sure that you are looking at the right mindy account?

**Comment by natashaarmbrust** [comment]
Yes! and I am .. I pressed on her search table view cell to see that I was following her

**Comment by natashaarmbrust** [comment]
Also if you look at the snippet above, it prints our Mindy as my follower but says her followers count is 0
