### ISSUE TITLE
Episode playing duration 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#149]
We should have an episode playing duration on the episode models. We need an endpoint for updating a list of episodes durations and a field on the episodes for duration (this could be percentage from 0 to 1)

**Comment by Jma353** [comment]
What does this mean

**Comment by natashaarmbrust** [comment]
@kevingreer  is on top of this. Sorry a bit confusing of an issue description.

**Comment by DanielNosrati** [comment]
#169 has fixed this
