### ISSUE TITLE
Series last updated seems to be inconsistent and sometimes wrong

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#152]
For example, for this series, the latest episode was September 20, 2016.
![img_0693](https://user-images.githubusercontent.com/14966713/32686573-c95bae44-c674-11e7-926c-3d8cffff5018.PNG)

However, it's last updated label is today 
![img_0694](https://user-images.githubusercontent.com/14966713/32686583-ec2f09b6-c674-11e7-9b68-d9c3d6ef87a3.PNG)
showing also debugger / lastUpdatedString output to show you that we successfully parse it but what backend is providing is wrong. 

<img width="517" alt="screen shot 2017-11-11 at 12 07 02 am" src="https://user-images.githubusercontent.com/14966713/32686581-e909b786-c674-11e7-85eb-6b8ef97fa55b.png">

The series below is another example if you need more references

![img_0695](https://user-images.githubusercontent.com/14966713/32686586-11791270-c675-11e7-8b37-eff7f7ee275b.PNG)

**Comment by Jma353** [comment]
Oh I think there was some miscommunication between what this means.  Right now "last_updated" returns the last time we checked for updated episodes based on the time we loaded the most recent podcast episode in.

**Comment by Jma353** [comment]
Now that I think about it this is actually pretty confusing to be honest.  If I see the podcast was "updated" a day ago I'd believe the current info is correct.  But if I see the podcast was last "updated" a year ago, I'd believe the app is just not keeping track of the data.  Maybe we can ask @eileendai what her opinion is on a different word in this scenario.  Changing this to be the pub_date of the last published episode is a quick fix tho if that's the desired behavior.

**Comment by natashaarmbrust** [comment]
fixed with episode updates
