### ISSUE TITLE
Searching for users returns incorrect result

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#157]
When searching for users, I type in Kei and get no results but can type in K and get Keivan .. This probably has to do with Elastic Search but exact match should definitely return all results associated. 

![img_0706](https://user-images.githubusercontent.com/14966713/32808979-1ac41582-c963-11e7-9b88-66edc5de9add.PNG)
![img_0707](https://user-images.githubusercontent.com/14966713/32808981-1cdcad52-c963-11e7-896a-925f2078e978.PNG)

**Comment by ChenJesse** [comment]
Oh the elasticsearch stuff isn't in production yet
But I believe why this is happening is because our search is only searching on username, not real name, so Keivan's username is "Kanyewest"

**Comment by natashaarmbrust** [comment]
LOL. Ok, are we planning to add in elastic search anytime soon?

**Comment by natashaarmbrust** [comment]
If not, we should switch username searching to be username + Full name searching

**Comment by ChenJesse** [comment]
Hmm yeah I think the bugs kinda pushed it back, its mostly actually deploying the stuff to the server that is the bottleneck and I think Joe is busy with other things, and idk wtf I'm doing with devops so...

But yeah I can make the naive search also do full name searching easily, I'll do that for now

**Comment by Jma353** [comment]
LOL just saw this haha.  @ChenJesse will check your branch this Friday when I have ample free time.  We can deploy ElasticSearch within the next 2 weeks for sure - it's something that will benefit from our open beta's feedback.

**Comment by Jma353** [comment]
For now, @natashaarmbrust Jesse's quick fix should make finding users better.
