### ISSUE TITLE
isSubscribed returns the wrong result for a user who is not me

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#160]
In when I fetch a users subscriptions if that user is not me it always returns `isSubscribed = true`. For example, below from Daniel's profile it gives me `isSubscribed = true` even though I am not subscribed to the podcast below. The field should be reflective of the requesting user not the userId parameter in the endpoint. 

<img width="254" alt="screen shot 2017-11-15 at 7 27 00 pm" src="https://user-images.githubusercontent.com/14966713/32867455-2de4c994-ca3b-11e7-81ac-8e2f8e05fd96.png">
<img width="267" alt="screen shot 2017-11-15 at 7 26 49 pm" src="https://user-images.githubusercontent.com/14966713/32867457-2f430ed6-ca3b-11e7-99c8-2b43941d8aaa.png">

**Comment by Jma353** [comment]
[Code pointer](https://github.com/cuappdev/podcast-backend/blob/master/src/app/pcasts/controllers/get_user_subscriptions_controller.py)

**Comment by Jma353** [comment]
@ChenJesse I believe this is you

**Comment by ChenJesse** [comment]
Hmm I wrote subscriptions but I didn't write the `is_subscribed` stuff, that was added on later, and I think this is more about the series model, I'll look into it anyways

**Comment by Jma353** [comment]
we need to be able to get another user's subscriptions but reflect the `is_subscribed` boolean for the user currently logged in.

**Comment by ChenJesse** [comment]
Ah I see it's nested, found the bug
