### ISSUE TITLE
Subscription model

### ISSUE THREAD

**Issue by amit-mizrahi** [cuappdev/podcast-backend#17]
Denormalized subscription model schema, optimized for displaying list of people subscribed to a series and list of series person is subscribed to.

    {
        "userId": 123,
        "seriesId": 456,
        "username": "abc",
        "userImageUrl": "image1.jpg",
        "userFirstName": "name",
        "userLastName": "name",
        "seriesTitle": "title",
        "seriesImageUrlSm": "image2.jpg"
    }

**Comment by Jma353** [comment]
Hmm I like it... but it might make it easier on us if we arrange the denormalized JSON in a way similar to how I do it in this [this issue](https://github.com/cuappdev/podcast-backend/issues/19) for `recommendations`.  Basically just formatting, but important to note.

**Comment by amit-mizrahi** [comment]
Ok. Copied your schema from recommendations and modified it below:

```
{
  "type": "subscription",
  "seriesTitle": "A Podcast Series Title",
  "imageUrlSm": "Small Image URL",
  "imageUrlLg": "Large Image URL",
  "user": {
    "id": "id2",
    "imageUrl": "https://goo.gl/L37gfS",
    "firstName": "Joe",
    "lastName": "Antonakakis",
    "username": "jma353"
    // More user 'person' user fields
  }
}
```

**Comment by amit-mizrahi** [comment]
^ Will be using this.
