### ISSUE TITLE
isFollowing field incorrectly set in FeedElements 

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#184]
`isFollowing` is incorrectly set when fetching feed elements 

For example, 
<img width="298" alt="screen shot 2018-02-15 at 1 55 22 am" src="https://user-images.githubusercontent.com/14966713/36244421-1da7f78a-11f4-11e8-9727-ad3b85eff902.png">
<img width="298" alt="screen shot 2018-02-15 at 1 55 28 am" src="https://user-images.githubusercontent.com/14966713/36244423-1e8d758a-11f4-11e8-9a74-216bf7678e3d.png">

I am following Yoo and thats why she showed up on my feed but the user object's `isFollowing` field is `false`

**Comment by natashaarmbrust** [comment]
I'm not sure who wants to take on this bug, @DanielNosrati or @kevingreer but should be an easy quick fix

**Comment by kevingreer** [comment]
So the `isFollowing` field exists but it false when it should be true? Did you populate that profile page using the info from the feed response?

**Comment by natashaarmbrust** [comment]
It is not included in the response json

**Comment by natashaarmbrust** [comment]
Yes we populate the profile view from the feed without making another request for the user

**Comment by natashaarmbrust** [comment]
fixed with recent deployment
