### ISSUE TITLE
Duplicate series in discover

### ISSUE THREAD

**Issue by mindylou** [cuappdev/podcast-backend#203]
For example, page 0 (offset 0 max 10) and page 2 (offset 10 max 10) both contain "This American Life":

![image](https://user-images.githubusercontent.com/20246620/37192920-d070f400-2335-11e8-85bb-7c9e3101759c.png)

**Comment by natashaarmbrust** [comment]
We are going to increase our pageSize for now but we should fix this ASAP

**Comment by DanielNosrati** [comment]
#209 will solve this
