### ISSUE TITLE
In the FindFacebookEndpoint can we add a query parameter for is following

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#207]
As of now, we get the top 20 facebook friends and display them on the feed if you are not following. however, once you are following 20 facebook friends we no longer have suggestions on the feed. Since this endpoint is pagenated, the filtering should be done on the backend. Let's add a query parameter (let's saying` returnFollowing`: [`true` or`false`]). If we don't add this query parameter in the request we should be returned everyone regardless of if we are following or not following them.

**Comment by DanielNosrati** [comment]
See PR for usage details
