### ISSUE TITLE
isSubscribed field not being returned in Discover endpoints

### ISSUE THREAD

**Issue by natashaarmbrust** [cuappdev/podcast-backend#208]
for the endpoint `/discover/series/user/`, the json is missing `is_subscribed` just for `The Daily` podcast .. like what?? idk weird but but its happening. All the other series returned have the field set
<img width="284" alt="screen shot 2018-03-14 at 3 56 07 pm" src="https://user-images.githubusercontent.com/14966713/37427591-46ac1078-27a0-11e8-8cc0-843bbcf64c9a.png">
<img width="149" alt="screen shot 2018-03-14 at 3 55 59 pm" src="https://user-images.githubusercontent.com/14966713/37427594-4835db5e-27a0-11e8-86ce-56bd7cc14491.png">

**Comment by natashaarmbrust** [comment]
there is also no `last_updated` field

**Comment by natashaarmbrust** [comment]
just for `The Daily` tho

**Comment by DanielNosrati** [comment]
fixed by pr
