### ISSUE TITLE
Bookmark endpoints

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/podcast-backend#37]
get bookmarks - should return a user's bookmarks and only accessible if the requested userID matches the session token of that user (i.e. I shouldn't be able to see anyone else's bookmarks, only my own)

add bookmark - should add a bookmark if it doesn't exist already

delete bookmark - should delete a bookmark if it exists

**Comment by Jma353** [comment]
title, pubDate, duration, seriesTitle, id, numRecommendations, audioUrl

**Comment by amit-mizrahi** [comment]
@Jma353 Are you handling this, or should I?

**Comment by Jma353** [comment]
I got it!

**Comment by Jma353** [comment]
Done, need to test
