### ISSUE TITLE
Listen History

### ISSUE THREAD

**Issue by dennisfedorko** [cuappdev/podcast-backend#38]
We should be able to log all of the podcasts a user has listened to, as well as retrieve them to display to the user, and allow the user to delete their history. Access should be allowed only to a user who owns the auth token for the userID they are requesting.

get listen history - returns a list of all episodes a user has listened to

add episode to history - add an episode to the list of episodes the user has listened to

remove episode from history - remove a single episode from the user's history

delete full listen history - clear entire history for a user

**Comment by Jma353** [comment]
Sounds good to me

**Comment by Jma353** [comment]
Starting to work on this today

**Comment by Jma353** [comment]
ae5a6a80f4fc0429f9c0c2e6fe20b39b263ef8ab
