### ISSUE TITLE
ON DELETE CASCADE only when necessary

### ISSUE THREAD

**Issue by Jma353** [cuappdev/podcast-backend#68]

**Comment by ChenJesse** [comment]
if you have too much on your plate, I can just make the changes with my PR...it's just removing the `cascade='all,delete'` for all the `db.relationship` for 
```
bookmark.py
episode.py
session.py
subscription.py
```
right?

**Comment by Jma353** [comment]
Looks like you did this - great job.  Close this task when you merge in PR.
